// Downloads embeddable TTF fonts (Tinos = Times New Roman metric-compatible
// serif for the ABNT body; Montserrat = elegant sans for titles) and writes
// them as a base64 pdfmake "vfs" module at src/pdf/fonts/vfs.ts.
//
// Run once with: npm run build:fonts
// The legacy Google Fonts CSS endpoint serves TTF (not woff2) when queried
// with an old user-agent, which is exactly what pdfmake needs to embed.

import { writeFileSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const OUT = resolve(__dirname, "../src/pdf/fonts/vfs.ts");

const LEGACY_UA = "Mozilla/4.0";

// Fonts pulled from the Google Fonts legacy CSS endpoint (TTF).
const FONTS = [
  { file: "Tinos-Regular.ttf", family: "Tinos", variant: "400" },
  { file: "Tinos-Bold.ttf", family: "Tinos", variant: "700" },
  { file: "Tinos-Italic.ttf", family: "Tinos", variant: "400italic" },
  { file: "Tinos-BoldItalic.ttf", family: "Tinos", variant: "700italic" },
  { file: "Montserrat-SemiBold.ttf", family: "Montserrat", variant: "600" },
  { file: "Montserrat-Bold.ttf", family: "Montserrat", variant: "700" },
  // Monochrome emoji fallback so emoji render as clean B&W glyphs instead of
  // tofu boxes (PDF engines cannot embed COLOR emoji fonts).
  { file: "NotoEmoji-Regular.ttf", family: "Noto Emoji", variant: "400" },
];

// Direct-URL fonts. DejaVu Serif has very broad Unicode coverage (Greek,
// arrows, math operators, micro sign, etc.) and is used as the glyph
// fallback so symbols like →, μ, ≈, ≤ render instead of becoming blanks.
const DIRECT_FONTS = [
  {
    file: "DejaVuSerif.ttf",
    url: "https://cdn.jsdelivr.net/npm/dejavu-fonts-ttf@2.37.3/ttf/DejaVuSerif.ttf",
  },
  {
    file: "DejaVuSerif-Bold.ttf",
    url: "https://cdn.jsdelivr.net/npm/dejavu-fonts-ttf@2.37.3/ttf/DejaVuSerif-Bold.ttf",
  },
];

async function ttfUrl(family, variant) {
  const css = await fetch(
    `https://fonts.googleapis.com/css?family=${encodeURIComponent(family)}:${variant}`,
    { headers: { "User-Agent": LEGACY_UA } }
  ).then((r) => r.text());
  // The legacy CSS lists @font-face blocks; pick the .ttf src for this variant.
  const matches = [...css.matchAll(/url\((https:\/\/[^)]+\.ttf)\)/g)].map((m) => m[1]);
  if (!matches.length) throw new Error(`No TTF found for ${family}:${variant}`);
  return matches[0];
}

async function main() {
  const vfs = {};
  for (const f of FONTS) {
    process.stdout.write(`Fetching ${f.file} ... `);
    const url = await ttfUrl(f.family, f.variant);
    const buf = Buffer.from(await fetch(url).then((r) => r.arrayBuffer()));
    vfs[f.file] = buf.toString("base64");
    console.log(`${(buf.length / 1024).toFixed(0)} KB`);
  }
  for (const f of DIRECT_FONTS) {
    process.stdout.write(`Fetching ${f.file} ... `);
    const buf = Buffer.from(await fetch(f.url).then((r) => r.arrayBuffer()));
    if (buf.length < 1000) throw new Error(`Bad download for ${f.file}`);
    vfs[f.file] = buf.toString("base64");
    console.log(`${(buf.length / 1024).toFixed(0)} KB`);
  }

  const body =
    "// AUTO-GENERATED by scripts/build-fonts.mjs — do not edit by hand.\n" +
    "// Base64-encoded TTF fonts embedded into the PDF via pdfmake's vfs.\n" +
    "/* eslint-disable */\n" +
    "export const vfs: Record<string, string> = " +
    JSON.stringify(vfs, null, 0) +
    ";\n";

  mkdirSync(dirname(OUT), { recursive: true });
  writeFileSync(OUT, body, "utf8");
  console.log(`\nWrote ${OUT} (${(body.length / 1024 / 1024).toFixed(2)} MB)`);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
